### ISSUE TITLE
Better info in the phragmen page.

### ISSUE THREAD

**Issue by kianenigma** [Colm3na/polkastats-v3#79]
Hey, I am the Phragmen guy at parity. I have some notes for you about the page:

1. I would not call it _phragmen_ but rather something like _election prediction_. Soon we will change this election to something else and the keyword phragmen does not make much sense anymore. 

2. Make sure you run offline-elections with the exact parameters explained here: https://github.com/paritytech/substrate-debug-kit/tree/master/offline-election#builders

3. If you confirm that you are using this tool (so far I just assumed this), I will add you to the list of builders there. 

Also, I will soon work on compiling this to wasm and providing it as javascript package. Let me know if you'd be interested in trying it out first hand!

**Comment by mariopino** [comment]
Hey @kianenigma, thanks a lot for fixing the json export, all your suggestions were implemented/in production right now:

- Renamed Phragmen to Election prediction.
- Updated `offline-election` to latest version, run it using 10 iterations and reduce as stated in your reference doc.

For sure I can confirm we are using substrate-dev-kit/offline-election :-), would be nice to be included in builders.

Btw, sure we want to beta test the new javascript implementation when available,
